# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'BDTestsUnitTests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BDTestsUnitTests
  pod 'Alamofire', '~> 4'
  pod 'OHHTTPStubs' # Default subspecs, including support for NSURLSession & JSON etc
  pod 'OHHTTPStubs/Swift' # Adds the Swiftier API wrapper too

  target 'BDTestsUnitTestsTests' do
      pod 'BDTestsUI', :git => 'https://github.com/bytedissident/BDTestsUI'
    inherit! :search_paths
    # Pods for testing
  end

  target 'BDTestsUnitTestsUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'BDTestsUI', :git => 'https://github.com/bytedissident/BDTestsUI'
    pod 'Alamofire', '~> 4'
    pod 'OHHTTPStubs' # Default subspecs, including support for NSURLSession & JSON etc
    pod 'OHHTTPStubs/Swift' # Adds the Swiftier API wrapper too
  end

end
