# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BDTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
   pod 'Alamofire', '~> 4.0'

	pod 'OHHTTPStubs' # Default subspecs, including support for NSURLSession & JSON etc
	pod 'OHHTTPStubs/Swift' # Adds the Swiftier API wrapper too
  # Pods for BDTest

  target 'BDTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BDTestUITests' do
    inherit! :search_paths
    
    
    pod 'OHHTTPStubs' # Default subspecs, including support for NSURLSession & JSON etc
    pod 'OHHTTPStubs/Swift' # Adds the Swiftier API wrapper too
    # Pods for testing
  end

end
