# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BDTestsExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestMe
  # pod 'BDTestsUI', :git => 'https://github.com/bytedissident/BDTestsUI'
  pod 'BDTests', :git => 'https://github.com/bytedissident/BDTests'
  pod 'Alamofire'



  target 'BDTestsExampleUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'BDTests', :git => 'https://github.com/bytedissident/BDTests'
    #pod 'BDTestsUI', :git => 'https://github.com/bytedissident/BDTestsUI'
  end

end
