# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BDTestsExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BDTestsExample
  pod 'BDTests', :git => 'https://github.com/bytedissident/BDTests'


  target 'BDTestsExampleTests' do
    inherit! :search_paths
    # Pods for testing
    #pod 'BDTests', :git => 'https://github.com/bytedissident/BDTests'
  end

  target 'BDTestsExampleUITests' do
    inherit! :search_paths
    # Pods for testing
    #pod 'BDTests', :git => 'https://github.com/bytedissident/BDTests'
  end

end
